const ACTIONS = {
  REQUEST_QUERY: 'REQUSET_QUERY',
  REQUEST_SET_RATE: 'REQUEST_SET_RATE',
  REQUEST_SET_LOOP: 'REQUEST_SET_LOOP',
  FULFILLED_QUERY: 'FULFILLED_QUERY',
  FULFILLED_SET_RATE: 'FULFILLED_SET_RATE',
  FULFILLED_SET_LOOP: 'FULFILLED_SET_LOOP',
};

export default ACTIONS;
